src/components/project/ProjectPlanAdminBlock.tsx, src/components/project/ProjectPlanAdminModal.tsx, src/components/project/ProjectPlanCard.tsx, src/components/project/ProjectPlanProductSelector.tsx
1. change style of `projectPlanAdminModol` on projectPlanCard.
2. now, we can delete `planProduct` in the plan.
3. use ellipsis to replace the character which is too long to show.
=> [BUGFIX] fix projectPlanAdminModel style && update planProducts in db

src/pages/ProgramProgressCollectionAdminPage.tsx
=> [BUGFIX]  status is empty if content type is exercise

src/components/appointment/AppointmentPlanCollectionTabs.tsx, src/components/appointment/AppointmentScheduleImportModal.tsx, src/components/blog/BlogPostBasicForm.tsx, src/hasura.d.ts, src/helpers/translation.ts, src/hooks/blog.ts, src/pages/MemberContractCreationPage/ReferralMemberSelector.tsx, src/types/blog.ts, yarn.lock
- admin/blog/:postId can edit post.source
=> [FEATURE] admin post.source

src/components/program/ExerciseAdminModal.tsx, src/components/program/PracticeAdminModal.tsx, src/components/program/ProgramContentAdminItem.tsx, src/components/program/ProgramContentAdminModal.tsx
+ fetch programContentBody in modal component
+ remove resetFields on submit event
+ add resetFields on cancel event
=> [BGUFIX] fix programContentBody data flow

src/hasura.d.ts, src/pages/ProgramProgressCollectionAdminPage.tsx, src/pages/translation.ts
=> [FEATURE] add date picker to program progress search

package.json, src/pages/ProgramProgressCollectionAdminPage/ProgramProcessBlock.tsx, yarn.lock
- modify firstWatchedAt and lastWatchedAt 's format when export
=> [BUGFIX] modify program progress's watch time export

src/components/sale/OrderExportModal.tsx, src/components/sale/SaleCollectionAdminCard.tsx
- add PAYING status in order filter
=> [BUGFIX] add PAYING status

src/pages/CertificateAdminPage/CertificateEligibilityListBlock.tsx
=> [BUGFIX] fix refetch

package.json, src/pages/CertificateAdminPage/CertificateAdminPage.tsx, src/pages/CertificateAdminPage/CertificatePreviewModal.tsx, src/pages/translation.ts, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json, yarn.lock
To preview certificate in certificate admin page.
=> [FEATURE] Implement certificate preview modal

src/components/programPackage/ProgramPackagePlanCollectionBlock.tsx, src/helpers/translation.ts, src/hooks/programPackage.ts, src/pages/ProgramPackageAdminPage.tsx
- Add sorting modal to `/admin/program-packages/<program_id>?tab=sales`.
- Fix plans list didn't order by position.
- Remove original position admin layout for editing plan position.
=> [FEATURE] Add sorting modal to program package plan

src/pages/AppSettingAdminPage.tsx
- fix can't update app_setting when value is empty
=> [BUGFIX] fix can't update app_setting when value is empty

src/hasura.d.ts, src/pages/ProgramProgressCollectionAdminPage/ProgramProcessBlock.tsx
-  fix exerciseStatus & watchedProgress for exam & exercise
=> [BUGFIX] fix exerciseStatus & watchedProgress

src/hasura.d.ts, src/helpers/translation.ts, src/hooks/appPage.ts, src/pages/CraftPageAdminPage/CraftPageBasicSettingBlock.tsx, src/pages/CraftPageAdminPage/CraftPageOpenGraphSettingBlock.tsx, src/pages/CraftPageAdminPage/CraftPageSeoSettingBlock.tsx, src/translations/locales/zh-tw.json, src/types/craft.ts
- add SEO & Open Graph settings block
=> [FEATURE] add SEO & Open Graph settings block

src/components/sale/OrderExportModal.tsx, src/hasura.d.ts, src/helpers/translation.ts
- Add fields 
- order created at
- order product ended at
=> [FEATURE] Add fields to order product export csv

src/components/admin/AdminMenu.tsx, yarn.lock
- add portfolio project module
=> [BUGFIX] add portfolio project module

src/components/form/OpenGraphSettingsBlock.tsx, src/helpers/translation.ts, src/translations/locales/zh-tw.json
=> [BUGFIX] add og:image tooltip

src/components/project/ProjectPortfolioSettingsForm.tsx, src/components/project/translation.ts, src/hasura.d.ts, src/translations/locales/zh-tw.json
- fix portfolio has same original source
=> [BUGFIX] fix portfolio has same original source

src/components/sale/OrderImportModal.tsx, yarn.lock
- revise error message when importing order
=> [BUGFIX] error message of import order

src/components/form/MemberSelector.tsx, src/pages/VoucherPlanCollectionAdminPage/VoucherPlanCollectionBlock.tsx
=> remove filter

src/components/project/ProjectPortfolioAuthorBlock.tsx, src/hasura.d.ts, yarn.lock
- use insert, delete instead of update
=> [BUGFIX] use insert, delete instead of update

src/hooks/program.ts
讓管理頁面和前台的 program_roles 使用相同的 ordering rules
ref: https://github.com/urfit-tech/lodestar-app/pull/263
=> [CHANGE] Align program roles ordering

src/components/sale/SaleCollectionAdminCard.tsx
=> [BUGFIX] add optional chaining

.vscode/settings.json, src/components/admin/AdminPublishBlock.tsx, src/components/project/ProjectCollectionBlock.tsx, src/components/project/ProjectCollectionTable.tsx, src/components/project/ProjectPublishAdminBlock.tsx, src/components/project/translation.ts, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
=> [BUGFIX] modify portfolio project

src/pages/AppBasicAdminPage/AppBasicAdminCard.tsx
=> [bugfix] logo setting change

src/components/common/DraggableItemCollectionBlock.tsx, src/hasura.d.ts, src/hooks/member.ts, src/pages/MemberPropertyAdminPage.tsx
自訂欄位開啟可讓會員編輯時，這邊會多顯示一個區塊「其他資料」
=> [bugfix] update backsite member property setting

src/components/blog/BlogExportModal.tsx, src/hasura.d.ts, src/pages/BlogCollectionAdminPage.tsx
don't set timestamp 
don't have dialog export csv
=> [update] blogexport setting

src/components/blog/BlogPostTable.tsx
YYYY-MM-DD HH：MM timezone format
=> [update] blog post table setting

src/components/sale/OrderExportModal.tsx, src/components/sale/translation.ts, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
- add shipping fee field in order export
=> [BUGFIX] add shipping fee field in order export

package.json
[React Uncaught ReferenceError: process is not defined](https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined)
=> [BUGFIX] fix hot reload

src/components/coupon/CouponPlanDescriptionTabs.tsx, src/hasura.d.ts, src/hooks/checkout.ts, src/types/checkout.ts
- fix can't export massive coupon codes
=> fix: can't export massive coupon codes

src/components/activity/ActivityTicket.tsx, src/components/activity/ActivityTicketsAdminBlock.tsx, src/components/common/ProductSkuModal.tsx, src/components/program/ProgramSubscriptionPlanAdminCard.tsx, src/components/programPackage/ProgramPackagePlanCollectionBlock.tsx, src/components/project/ProjectPlanCard.tsx, src/hasura.d.ts, src/hooks/channel.ts, yarn.lock
- delete and update product channel
- some layout
=> Bugfix/channel SKU layout

src/pages/ProgramProgressCollectionAdminPage/ProgramProcessBlock.tsx
=> update csv setting

src/hooks/member.ts, src/hooks/program.ts
=> fix: attachment null data

src/pages/MemberCollectionAdminPage.tsx
- app-owner
- general-member 含有 MEMBER_ADMIN 權限
- 找出同一 App 上，前 100 筆，被重複使用的手機號碼及其會員資料（單一電話電話被 2 名以上會員使用）
=> 顯示同一 App 上，前 100 筆，被重複使用的手機號碼及其會員資料

src/pages/MemberContractCreationPage/MemberContractCreationBlock.tsx, src/pages/MemberContractCreationPage/MemberContractCreationForm.tsx
=> feat: add create contract verify

src/pages/LearningOverviewPage/index.tsx
- modify recentLearningCount & recentLearningDuration duration from 7 days to 30 days
=> fix: modify recentLearningCount & recentLearningDuration duration

src/components/sale/ModifyOrderStatusModal.tsx
- fix can't change order status to success
=> fix: ModifyOrderStatusModal

src/components/form/ProductSelector.tsx, src/components/form/translation.ts, src/components/voucher/VoucherPlanAdminModal.tsx
ProductSelector add merchandise series type
+ GeneralPhysicalMerchandiseSpec，一般實體
+ GeneralVirtualMerchandiseSpec，一般虛擬
+ CustomizedPhysicalMerchandiseSpec，客製實體
+ CustomizedVirtualMerchandiseSpec，客製虛擬
=> feat: merchandise series type

package.json, src/components/voucher/VoucherPlanAdminModal.tsx, src/components/voucher/VoucherPlanCard.tsx, src/components/voucher/translation.ts, src/hooks/checkout.ts, src/pages/VoucherPlanCollectionAdminPage/VoucherPlanCollectionBlock.tsx, src/types/checkout.ts, yarn.lock
+ module name: voucher_pin_code 
+ voucher plan can set pin code
+ pin code is 4 - 6 numbers
=> feat: voucher pin code

src/components/podcastAlbum/PodcastAlbumCollectionTabs.tsx, src/hooks/podcastAlbum.ts
- Hide the podcast album if the "is_deleted" is true.
=> fix: hide podcast album is deleted

src/components/appointment/AppointmentPeriodCard.tsx, src/components/appointment/AppointmentRescheduleModal.tsx, src/hooks/appointment.ts
+ replace appointmentPlanAdmin with appointmentPlan
+ connect reschedule api
+ handleReschedule remove hasura gql
+ adjust appointment plan loading status
=> feat: reschedule api

src/hooks/order.ts, src/pages/SalesPage/SaleSummaryCard.tsx
(cherry picked from commit f49ffb1cdd277841fb669f97094f2f1737887564)
=> hotfix: order log query slow

src/components/sale/SalesLeadTable.tsx
Add checks to prevent errors during member transfer.
=> feature: add check for non existent member

src/components/admin/AdminMenu.tsx, src/components/form/PermissionInput.tsx, src/components/form/translation.ts, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
- add certificate permissions
- update permission display text
=> feature: certificate permissions

src/hooks/sales.ts
Exclude two states:
1. star equals -9999
2. excluded_at has a value
=> fixbug: exclude cases of removed items from the list

src/components/sale/OrderExampleData.ts, src/components/sale/OrderImportModal.tsx, src/components/sale/SaleCollectionExpandRow.tsx
- Replace sample orders
- Display hours, minutes, seconds
=> fixbug: set endedAt time

src/components/program/ExerciseAdminModal.tsx, src/components/program/ProgramContentAdminModal.tsx, src/hooks/program.ts
- content is not updated after saving
=> fixbug:the content is not updated after saving

src/components/craft/inputs/SizeStyleInput.tsx, src/components/craft/settings/ImageSettings.tsx, src/helpers/index.ts
=> feat: img setting

src/components/program/ProgramContentAdminItem.tsx, src/components/program/ProgramContentAdminModal.tsx, src/components/program/ProgramContentSectionAdminCard.tsx, src/components/program/translation.ts, src/hooks/program.ts, src/images/icon/pin-v-2.svg, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json, src/types/program.ts
- course content list expansion feature
=> feat:course content list expansion feature

src/pages/ProgramAdminPage/ProgramStructureAdminBlock.tsx
- default expand first chapter
=> fix: default expand first chapter

src/pages/ProgramAdminPage/ProgramStructureAdminBlock.tsx
- modify default expand all chapters
=> fixbug:modify default expand all chapters

src/components/task/MemberTaskAdminModal.tsx
+ when meeting hours change, rebuild meeting
=> fix:rebuilding meetings when they frequently change

src/components/member/MemberNoteAdminItem.tsx, src/pages/NoteCollectionPage.tsx
=> fixbug: automatically add memberNote URL address

src/components/member/MemberNoteAdminItem.tsx, src/pages/NoteCollectionPage.tsx
=> fixbug:fix missing name of admin path in URL

src/components/member/MemberNoteAdminItem.tsx, src/components/member/MemberNoteAdminModal.tsx
- remove member note admin permission
=> fixbug:remove member note admin permission

src/components/program/ProgramSubscriptionPlanAdminCard.tsx, src/components/program/programPlanAdminModals/MembershipPlanModal.tsx, src/components/program/programPlanAdminModals/formItem/MembershipCardItem.tsx, src/helpers/translation.ts, src/hooks/program.ts, src/pages/ProgramAdminPage/ProgramPlanAdminBlock.tsx, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json, src/types/program.ts
=> fixbug:add membershipCard module and modify design

src/components/member/MemberNoteAdminItem.tsx
modify member note transcript permission
=> fixbug: modify member note transcript permission

src/components/coin/MemberCoinAdminBlock.tsx
=> fix:fix coinLog display issue

src/components/coin/MemberCoinAdminBlock.tsx, src/components/common/CoinSendingModal.tsx
Making negatives and decimals allowed on coin admin block with chips showing negative coins colored yellow
=> feat: making negatives and decimals allowed on coin admin block with chips showing negative coins colored yellow

src/helpers/translation.ts, src/hooks/program.ts, src/pages/ProgramAdminPage/ProgramPlanAdminBlock.tsx, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
=> feat: ProgramPlanAdminBlock add programPlanSorts

src/components/program/ProgramSubscriptionPlanAdminCard.tsx, src/components/program/programPlanAdminModals/PeriodPlanModal.tsx, src/components/program/programPlanAdminModals/PerpetualPlanModal.tsx, src/components/program/programPlanAdminModals/ProgramPlanModal.tsx, src/components/program/programPlanAdminModals/SubscriptionPlanModal.tsx, src/pages/ProgramAdminPage/ModalTriggerButton.tsx, src/pages/ProgramAdminPage/ProgramPlanAdminBlock.tsx, src/types/programPlan.ts
=> refactor: ProgramPlanAdminBlock plan modal

src/pages/ProgramAdminPage/ProgramBasicForm.tsx, src/pages/ProgramAdminPage/ProgramCoverForm.tsx
-【後台】切換版型處，預設為：標準版型。
-【後台】當預設欄位為上傳影片檔時，直接給一張固定的圖示示意已上傳
=> fix:program layout template module 0620

src/components/craft/settings/ImageSettings.tsx
- fix the issue where full size image can not be set
=> fix:the issue where full size image can not be set

src/hooks/program.ts, src/hooks/programLayoutTemplate.ts
=> feat: remove is_active

src/components/announcement/AnnouncementPreviewModal.tsx, src/pages/AnnouncementCollectionPage/AnnouncementCollectionPage.tsx, src/pages/AnnouncementPage/AnnouncementPage.tsx
=> feat: add preview announcement model

src/components/program/ExerciseAdminModalBlock.tsx, src/components/program/PracticeAdminModalBlock.tsx, src/components/program/ProgramContentAdminItem.tsx, src/components/program/ProgramContentAdminModal.tsx, src/hooks/program.ts, src/pages/ProgramAdminPage/ProgramPublishBlock.tsx, src/types/program.ts
adjust data flow for programContent
=> feat: fetch program content data in modal

src/components/task/MemberTaskAdminBlock.tsx, src/components/task/MemberTaskAdminModal.tsx, src/hooks/service.ts, src/types/member.ts
+ Google Meet will be displayed depending on the meet-service module
+ When dueAt changes, check if the meeting is valid.
=> feat: Integrate the meeting with google meet

src/components/member/MemberCreationModal.tsx
insert email should convert to lower case
=> feat: update email to be converted to lowercase in MemberCreationModal

src/components/program/ExerciseAdminModalBlock.tsx, src/components/program/PracticeAdminModalBlock.tsx
=> feat: Add overlay z-index style to dropdowns in modal

src/components/task/MemberTaskAdminModal.tsx, src/hooks/service.ts
Remove the Google Meet-related check restrictions.
=> feat:In response to business needs, relax the meeting rules

src/components/common/ItemsSortingModal.tsx
fix: corrected wrong parameter position of propEq function and refactored to make structure clearer
=> fix: corrected wrong parameter position of propEq function and refactored to make structure clearer

src/components/project/ProjectCollectionTabs.tsx
=> feat: project sorting

src/pages/NewMemberContractCreationPage/index.tsx
feat: showing products according to specific permission group in new member contract
=> feat: showing products according to specific permission group in new member contract

src/components/program/ExternalLinkAdminModalBlock.tsx
feat: external link validating non-repeated links
=> feat: external link validating non-repeated links

src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx
feat: new contract auto complete order payment delivery upon cash as payment method and no manual invoice
=> feat: new contract auto complete order payment delivery upon cash as payment method and no manual invoice

src/components/member/MemberPropertyAdminForm.tsx
feat: allow blank value of selectable member property
=> feat: allow blank value of selectable member property

src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx, src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx, src/pages/NewMemberContractCreationPage/index.tsx
Feat: round invoice item details in new contracts
=> Feat: round invoice item details in new contracts

src/components/sale/PaymentCard.tsx, src/hooks/orderReceivable.ts, src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx
fix: catastrophic consequence from receivable order in new contract
=> fix: catastrophic consequence from receivable order in new contract

src/components/sale/OrderDetailDrawer.tsx, src/components/sale/PaymentCard.tsx, src/helpers/index.ts, src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx, src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx, src/pages/NewMemberContractCreationPage/index.tsx
Change the judgment to check the continuous letters at the beginning of the string.
=> fix: check box disable logic

src/components/sale/MemberPhoneModal.tsx
=> bugfix:resolve cache blocking second update

src/components/sale/SaleCollectionExpandRow.tsx
feat: show indices of failed manual invoices on new contract
=> feat: show indices of failed manual invoices on new contract

src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
=> bugfix: fix type error of paymentDueDate

src/components/contract/MemberContractAdminBlock.tsx, src/hooks/member.ts, src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx, src/pages/NewMemberContractCreationPage/index.tsx
建立複製合約按鈕，以便在建立新合約時，自動帶入複製之合約的資料。
=> feature:create copied data contract

src/components/sale/OrderDetailDrawer.tsx
fix: making invoices in new contract shown correctly
=> fix: making invoices in new contract shown correctly

src/components/sale/PaymentCard.tsx
=> feat: restore changeCheckoutMethod button

src/hooks/member.ts, src/pages/NewMemberContractCreationPage/index.tsx
=> fix: unable to copy order content

src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
feat: allowing weekly frequency of new contract shown according to products
=> feat: allowing weekly frequency of new contract shown according to products

src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
=> fix: adjust payment due day datetime to end of day (23:59)

src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
依客戶需求，將原本合約到期日的時間，從23:59:59改為 合約建立當下的時間
=> fix: change paymentDueDay ending time from end of day to right now time

src/pages/NewMemberContractCreationPage/MemberDescriptionBlock.tsx, src/pages/NewMemberContractCreationPage/index.tsx
=> fix: copy contract data set loading enable to get data before render

src/pages/NewMemberContractCreationPage/index.tsx
=> fix: add useEffect to ensure data is loaded before render

src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx, src/pages/NewMemberContractCreationPage/index.tsx
將預設日期帶入當下時刻 hh:mm，防止未更改付款到期日時，系統抓的時間為00:00
=> fix:show time in paymentDueDate to ensure order gets correct timing

src/hooks/productSelector.ts
修正 handleTreeSelect 單選模式下的陣列處理邏輯
- Trello 卡排：https://trello.com/c/x0hres1u
=> fix: correct single selection logic in product selector

src/components/sale/ModifyOrderStatusModal.tsx
hasura 資料更新，調整依照權限組篩選下拉選單時，重複顯示外幣帳號
=> feat:change bank optionName

src/components/form/translation.ts, src/translations/locales/de-de.json, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/ja.json, src/translations/locales/ko.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
=> feat:change task permission translation

src/components/sale/TransferModal.tsx
feat: searchable dropdown for managers while transferring leads
=> feat: searchable dropdown for managers while transferring leads

src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx
- 修正顯示數據不同步的問題。
- 修正稅額計算時機錯誤。
- Trello 卡牌：https://trello.com/c/vbMHlTDW
=> fix: fix data display sync issue and incorrect tax calculation timing

src/pages/AppBasicAdminPage/AppNavModal.tsx, src/pages/AppBasicAdminPage/translation.ts
=> feat:add Deutsh option in AppNavAdminCard

src/pages/AppBasicAdminPage/AppNavModal.tsx, src/pages/AppBasicAdminPage/translation.ts
=> fix:double ja option
