- src/components/admin/AdminModal.tsx
- src/components/member/MemberNoteAdminItem.tsx
- src/helpers/translation.ts
- src/pages/MemberAdminPage/MemberAdminLayout.tsx
- src/pages/MemberAdminPage/MemberSmsModal.tsx
- SMS validation, content includes Chinese
- SMS validation, content only contains English and numbers
- Hide duration when contact type is SMS
- Send SMS button loading state
- Sent SMS succeed message
> [UPDATE] Adjust send SMS layout and validation rule

- src/components/programPackage/ProgramPackageProgramConnectionModal.tsx
- src/hasura.d.ts
- 'delete_program_package_program' where condition is wrong
old:
```graphql
delete_program_package_program(where: { program_package_id: { _eq: $program_package_id } }) {
affected_rows
}
```
new:
```graphql
delete_program_package_program(where: { id: { _in: $delete_program_package_programs_id } }) {
affected_rows
}
```
- modify "delete_programs_id" to "delete_program_package_programs_id"
> [BUGFIX] fix can't insert program in program package

- src/pages/MediaLibraryPage/MediaLibraryUsageCard.tsx
- modify chart color and text
- requirement
(ignore)1.寫 metabase 查看哪些客戶用量超過
2.圖表調整顏色，目前顏色與後台使用的不一致
Duration: #4ED1B3
Watched: #4C5B8F
3.圖表的圖說是顯示
WatchedSeconds -> 改為「WatchedMinutes」應該是分鐘不是秒
> fix: modify chart color and text

- src/components/craft/settings/SectionSettings.tsx
- src/components/craft/translation.ts
- src/translations/locales/en-us.json
- src/translations/locales/id.json
- src/translations/locales/vi.json
- src/translations/locales/zh-cn.json
- src/translations/locales/zh-tw.json
1. add "none" button in SectionSetting.tsx to provide default style when choose horizontal and vertical align.
2. translate "無" to every language.
> fix: modify craft align

- src/components/project/ProjectCollectionBlock.tsx
- src/components/project/ProjectCollectionTable.tsx
- src/components/project/ProjectCollectionTabs.tsx
- fix ProjectPortfolio published tab display bug
- 後臺右邊手動「專案排序」功能先拿掉，修正專案重複的問題，且發布時間最新的會往前排。
requirement:
取消發佈再重新發佈，作品列表多了一個重複的「Maserati Greacale 【馭見不凡篇】」
> fix: ProjectPortfolio published tab display bug

- src/components/activity/ActivityCollectionTabs.tsx
- modify finished activities query condition
requirement:
後台活動列表頁找不到 應該是判斷那邊有問題
https://ezlearn.mdnkids.com/admin/activities/eaa5b633-f729-431e-bc08-108c25a41e83
DC：https://discord.com/channels/753127151578120273/1125381013263101974/1125382480636153866
> fix: modify finished activities query condition

- src/pages/PracticeCollectionAdminPage.tsx
- modify GET_PRACTICE_PREVIEW_COLLECTION condition for practice search
requirement:
https://www.kimibarre.net/admin/practices
這個頁面中，無法以使用者名稱搜尋繳交的作業。
經查發現：送出的 variable 應該要是
```
{
"condition": {
"_or": [
{
"member": {
"name": {
"_like": "%洪璟旎%"
}
}
},
{
"title": {
"_like": "%洪璟旎%"
}
}
],
......
"limit": 20
}
```
原本送出的是
```
{
"condition": {
"_or": [
{
"member": {
"username": {
"_like": "%洪璟旎%"
}
}
},
{
"title": {
"_like": "%洪璟旎%"
}
}
],
......
"limit": 20
}
```
據改即可。
> fix: modify GET_PRACTICE_PREVIEW_COLLECTION condition

- src/components/activity/ActivityCollectionTabs.tsx
- fix ActivityCollectionTabs refetch activities bug when change tab
requirement:
https://discord.com/channels/753127151578120273/1125381013263101974
> fix: remove ActivityCollectionTabs onChange event

- src/components/podcast/PodcastProgramPlanForm.tsx
- src/components/podcast/translation.ts
- src/hooks/podcast.ts
- src/pages/PodcastProgramAdminPage.tsx
- src/translations/locales/en-us.json
- src/translations/locales/id.json
- src/translations/locales/vi.json
- src/translations/locales/zh-cn.json
- src/translations/locales/zh-tw.json
- src/types/podcast.ts
- add not individually sale checkbox in PodcastProgramPlanForm
requirement:
在銷售方案的頁面上，希望可以勾選「無單集銷售」；勾選後，底下「定價」與「優惠價」區域可以直接 display: none; 。
https://samplepage.kolable.app/admin/podcast-programs/7fe131c1-6db6-4e61-acc6-c9313d88c24d?tab=plan
> feat: add not individually sale checkbox in PodcastProgramPlanForm

- src/components/admin/CategoryAdminCard.tsx
- src/helpers/translation.ts
- src/translations/locales/zh-cn.json
- src/translations/locales/zh-tw.json
需求
問題：如果"課程分類"有被掛入到課程中，會無法直接刪除課程分類，出現錯誤訊息，有許多用戶看到錯誤訊息不知道代表什麼意思，希望這邊可以做相關翻譯
錯誤訊息：GraphQL error: Foreign key violation. update or delete on table "category" violates foreign key constraint "program_category_category_id_fkey" on table "program_category"
demo測試：https://demo.lodestar-dev.cc/admin/program-category
進到這個頁面，刪除「不能直接刪除唷～」分類，即可重現
因此：
遇到客戶從後台把課程刪除（系統上是封存）
然後要把分類清空
因為被封存的課程還掛上分類的關係，所以刪不掉分類
(1)
希望可以直接改成：刪除分類時，就把課程上掛的分類也清掉，讓分類能順利清空
部落格、活動、專案...等也都是一樣的問題
(2)
清除時希望能跳警示告知
文案：
刪除後會直接移除曾掛此項目的課程分類，確定要刪除嗎？
[取消] [刪除]
→ 建議所有產品的分類都檢查一輪～～
> fix: can't delete category

- src/components/common/AdminRouter.tsx
- src/components/layout/DefaultLayout.tsx
- src/hooks/data.ts
- src/pages/DeactivatePage.tsx
因應欄位調整，故儲存流量蓋版程式碼需要進行調整
---
儲存流量的部份因為欄位有調整，所以要改動程式碼，目前的流量限制需要抓 app_plan 的 options 中的值，目前每個客戶的 app_plan_id 已設定完成，就差儲存流量限制已到的蓋版程式碼需要調整，方可上線
另外也請注意，目前只有「影片儲存量」以及「影片觀看流量」這兩個限制，options 中的 sms 跟 max_other 是因應合約規格先設定好的，目前沒有 table 記錄這件事，所以請先略過，「影片儲存量」以及「影片觀看流量」這兩個流量使用請看 app_usage，值都是「秒」，app_plan 的 options 紀錄的數值是「分鐘」，所以請記得正確計算
以上，跟程式碼、資料庫相關有不太理解的地方可以再問 Lois
當初跟 RD 討論 options 的訊息連結：https://discord.com/channels/753127151578120273/1113247074088144998/1133407233582047324
by Lois
1. 將原本拿取 maxVideoDuration 和 maxVideoWatch 從 「app 的 option」變成「app_plan 的 option」
2. 在使用 dayjs 的元件補上「dayjs.extend(utc)」
3. 將 appPlan 加上型別
> fix: modify close site logic

- src/components/form/translation.ts
- src/pages/SalesPerformancePage/SalesPerformancePage.tsx
- yarn.lock
https://demo.lodestar-dev.cc/admin/sales/performance
先前有申請過 [機構]不得看到其他人，讓機構之間不得看到彼此業績
但好像沒有留哪一個機構是可以看的到所有人的
需要切一個權限選項為「查看所有業績」放置在業務管理底下[image.png](https://trello.com/1/cards/64e87d6d359e302e5df41a28/attachments/64e87da214fea8371680bce0/download/image.png)
新增「查看所有業績」權限選項
原「業績總表」改詞為「查看同機構業績」-->再改之前，先幫幫確認是否確實現在邏輯是無法看到不同機構業績 → 未調前可以看到其他機構
https://app.hubspot.com/contacts/41219621/record/0-5/1854983332
1. 在 Hasura 新增「SALES_VIEW_SAME_DEPARTMENT_PERFORMANCE_ADMIN」的「查看同機構業績」，並將「SALES_PERFORMANCE_ADMIN」名稱改名為「查看所有業績」
2. 調整「member」和「order_executor」的 select 權限判斷
3. 調整業務總表頁面和權限控制
> fix: modify SalesPerformancePage

- src/pages/MemberAdminPage/MemberHistoryAdminBlock.tsx
- src/translations/locales/zh-tw.json
由於 `program_content_log` 每五秒記錄一次用戶活動，因此連續觀看的情況下前端會出現多筆紀錄。例如，如果使用者持續觀看了 15 秒的內容，前端會出現三筆紀錄。這在 UI 上顯示為多筆短暫的歷程紀錄，而不是一筆連續的觀看歷程。
希望使用者歷史紀錄能夠顯示出如持續觀看 10 分鐘這樣的連續歷史紀錄。
1. **過濾有效的紀錄**：通過 `isValidLog` 函數過濾出那些 `ended_at` 和 `started_at` 差異超過 1 秒的紀錄
2. **降序排序紀錄**：對紀錄按照 `created_at` 欄位進行降序排序，確保處理是從最新到最舊的
3. **合併連續的紀錄**：使用 `reduce` 函數合併具有相同 `program_content` ID 的連續日誌。對於每一組連續日誌，計算最早的 `started_at` 和最晚的 `ended_at`，這樣可以將多筆短暫的歷史紀錄合併為一筆較長的歷史紀錄
1. 處理分母為0的情況
```
{v.program_content.duration > 0
? `${Math.round(((v.ended_at - v.started_at) / v.program_content.duration) * 100)}% watched`
: '0% watched'}
```
2. max={Math.round(v.program_content.duration)}
- 因為 `v.program_content.duration` 有可能不是整數
- 確保該值為整數
> feat: Merge consecutive content logs and process start and end times

- src/components/admin/AdminMenu.tsx
由於現在menu的銷售管理模組並沒有新增判斷權限，導致就算只有進入後台的一般權限也能進入頁面查看
新增權限判斷
若沒有銷售權限組，預設會跳個人設定頁面
查看所有銷售總額 GROSS_SALES_ADMIN
查看個人銷售總額 GROSS_SALES_NORMAL
查看所有銷售紀錄 SALES_RECORDS_ADMIN
查看消費者細項 SALES_RECORDS_DETAILS
查看個人銷售紀錄 SALES_RECORDS_NORMAL
> feat: add sales module permission group judgement to menu

- src/pages/SalesLeadDeliveryPage/SalesLeadDeliveryPage.tsx
Introduced tracking of the last time a manager was assigned to a member in the database schema and GraphQL mutation. The
`last_manager_assigned_at` field is now automatically set to the current timestamp when updating the lead manager, allowing for better tracking of manager assignment history and enhanced reporting capabilities.
> feat: add timestamp for manager assignment

- src/hooks/appointment.ts
Why
---
- Selecting the Ended tab shows an unfinished meeting.
What
---
- Fixed the issue where unfinished meetings will not appear when selecting the Ended tab.
Before
---
After
---
> fix: useAppointmentEnrollmentCollection finished condition ended_at

- src/pages/MemberCollectionAdminPage/MemberCollectionAdminPage.tsx
Why
---
- When SalesLeadDeliveryPage uses MemberCollectionBlock, the currentMembers brought in is undefined, thus an error occurs.
What
---
- Defaults the currentMembers props brought into MemberCollectionBlock to an empty array
> fix: MemberCollectionTableBlock currentMembers default empty array

- src/components/program/DisplayModeSelector.tsx
- src/components/program/ExerciseAdminModalBlock.tsx
- src/components/program/PracticeAdminModalBlock.tsx
- src/components/program/ProgramContentAdminModal.tsx
- src/components/program/translation.ts
- src/hooks/ebook.ts
- src/hooks/program.ts
- src/translations/locales/en-us.json
- src/translations/locales/id.json
- src/translations/locales/vi.json
- src/translations/locales/zh-cn.json
- src/translations/locales/zh-tw.json
- src/types/program.ts
- Move the option state of DisplayModeSelector to the parent component, because the changed state of displayMode needs to be used to determine whether the trialPercentage field appears.
- Determine the progress of e-book trial reading through the trialPercentage field.
- Determine the default value of trial reading through ebookTrialPercentageSetting of app_setting.
> feat: ebook trial percentage setting

- src/components/common/ProductCreationModal.tsx
- src/components/form/ProgramLayoutTemplateSelector.tsx
- src/hooks/data.ts
- src/hooks/program.ts
- src/hooks/programLayoutTemplate.ts
- src/pages/ProgramAdminPage/ProgramAdditionalSettingsForm.tsx
- src/pages/ProgramAdminPage/ProgramAdminPage.tsx
- src/pages/ProgramAdminPage/ProgramBasicForm.tsx
- src/pages/ProgramCollectionAdminPage.tsx
- src/types/program.ts
- other settings are developed as specific features and cannot be extended
- The standard template depended on database data
--- 
As a user with permissions, when I click to create a course, I should be able to choose a template. The options should include the standard template as well as all registered templates
- When a user with permissions chooses the standard template(標準版型) while creating a course, the selected ID should be set to null, and no data should be created in the program_layout_template_config table.
-  [5544e26](https://github.com/urfit-tech/lodestar-app-admin/pull/532/commits/5544e2686fbb7f2087801d7caf17c95f0d516cd8)
- [acd2cab](https://github.com/urfit-tech/lodestar-app-admin/pull/532/commits/acd2cabf49204f06ee5771465a3218599ebe01d0)
When the user selects a non-standard …
> Refactor Program Layout Template 

- src/components/task/MemberTaskAdminModal.tsx
only select BACKSTAGE_ENTER permission member
> feat: add backstage enter permission in member task create modal

- src/pages/NewMemberContractCreationPage/index.tsx
fix: making contract product shown according to permission group of admin rather than client
> fix: making contract product shown according to permission group of admin rather than client

- src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx
- src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
- src/pages/NewMemberContractCreationPage/index.tsx
https://trello.com/c/wZBaXV15
two condition
If there is no member type, accounts receivable cannot be selected.
If the member type does not start with "B" or "G", accounts receivable cannot be selected.
> feat: accounts receivable eligibility by member type

- src/pages/NewMemberContractCreationPage/MemberContractCreationBlock.tsx
- src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
- src/pages/NewMemberContractCreationPage/index.tsx
移除訂金 + 尾款的付款模式，統一改為一次性付款
- 此改動移除了原有的「訂金＋尾款」付款邏輯，並將付款流程調整為單一筆款項完成支付。
- Trello 卡片：https://trello.com/c/l1zas0Wo
> feat: remove deposit and balance payment mode

- src/components/admin/AdminMenu.tsx
- src/components/form/translation.ts
- src/components/sale/SaleCollectionAdminCard.tsx
- src/hooks/order.ts
- src/hooks/permission.ts
- src/pages/SalesPage/SaleSummaryCard.tsx
- src/pages/SalesPage/SalesPage.tsx
增加“讀取組內資料”，當被勾選時，只能看到所在權限組當中，組內成員創建的合約訂單
> feat: control sales and contract access with permission groups

- src/hooks/order.ts
- src/hooks/permission.ts
修正因為抓到的資料裡有undefined，而導致無法呈現資料的情況
刪除為拔除的conslo.log
> bugfix: prevent order list from crashing when data is missing

- src/components/admin/AdminMenu.tsx
- src/components/form/translation.ts
- src/components/task/MemberTaskAdminBlock.tsx
- src/hooks/task.ts
- src/pages/TaskCollectionPage.tsx
新增待辦清單permission。
若在權限組內勾選：讀取組內權限，則在待辦清單總覽，只會顯示與自己同權限組的成員的待辦清單
> Feature: add read group permission for task

- src/components/sale/SaleCollectionExpandRow.tsx
> feat:show payment due day in order info

- src/components/form/translation.ts
- src/hooks/sales.ts
- src/pages/SalesLeadPage.tsx
- src/types/sales.ts
目前有經辦同時隸屬於兩個不同服務的組別。
為了讓經辦可以在名單撥打選擇器中跨組別撥打，需要增加「讀取同權限組資料」的功能。
- Trello 卡片：https://trello.com/c/3PoTaswQ
> feat: support multi-division members in same division call list selector

- src/components/task/MemberTaskAdminBlock.tsx
- src/hooks/task.ts
篩選功能會影響排序邏輯，造成使用者無法正確依照『執行日期』查看最新項目。
修正後邏輯為：
- 篩選「執行日期」後，依照日期由新到舊排列（DESC）
- Trello 卡片：https://trello.com/c/AxzjK7b5
> bugfix: execution date filter causes incorrect sort order

- src/pages/NewMemberContractCreationPage/MemberContractCreationForm.tsx
> fix:enable time selection in paymentDueDate field

- src/components/sale/ModifyOrderStatusModal.tsx
- src/components/sale/PaymentCard.tsx
- src/components/sale/translation.ts
- src/helpers/translation.ts
新增收款帳號下拉選單，當結帳管道為 `銀行匯款` 時， 在交易紀錄中的 `變更交易紀錄 ` 內有下拉選單可以選取`收款帳號`。
選單內之`收款帳號` 依據登入者的權限組顯示對應的資料
> feat:add receiving account dropdown

- src/components/sale/PaymentCard.tsx
- 修正原本藍新顯示不正確的結帳管道資訊，讓用戶在前台可以正確看到所有付款選項
- Trello 卡排：
> fix: correct payment channel display logic

- src/components/member/MemberProfileBasicForm.tsx
遇到的問題：
在`名單撥打`，將電話標注無效，回到`會員基本資料`新增電話以及加入指派業務時，標記無效的電話會恢復成有效
更新：
已經標記無效的電話，即便在`會員基本資料`新增電話以及加入指派業務時，標記無效的電話保持無效
> feat:keep phone invalid when manager reassigned
